---
layout: post
title: Tumbleweed Release 20191121

release_available: false
release_reference_count: 10
release_reference_count_mail: 0
release_score: 97
release_stability_level: stable
release_version: 20191121
---

## mail (0:0)

no relevant mails

## bugs (10)

<!--more-->

- ~~[1157415: When removing python2, python3 errors on start](https://bugzilla.opensuse.org/show_bug.cgi?id=1157415)~~
- ~~[1157425: GNOME 'new user' window closed unexpectedly](https://bugzilla.opensuse.org/show_bug.cgi?id=1157425)~~
- ~~[1157428: drm/nouveau: call trace after recent update](https://bugzilla.opensuse.org/show_bug.cgi?id=1157428)~~
- ~~[1157429: \[Build 20191120\] openQA test fails in installation](https://bugzilla.opensuse.org/show_bug.cgi?id=1157429)~~
- ~~[1157430: drm/nouveau: call trace after recent update](https://bugzilla.opensuse.org/show_bug.cgi?id=1157430)~~
- [1157431: Inconsistent owner and group fpr /run/sddm](https://bugzilla.opensuse.org/show_bug.cgi?id=1157431)
- ~~[1157446: openconnect 8.06 ships python2 script](https://bugzilla.opensuse.org/show_bug.cgi?id=1157446)~~
- ~~[1157450: perl-XML-LibXSLT-1.96 fails to build in i586](https://bugzilla.opensuse.org/show_bug.cgi?id=1157450)~~
- [1157462: libdbus-1 uses abort() which is an absolute nogo for a system library](https://bugzilla.opensuse.org/show_bug.cgi?id=1157462)
- ~~[1157498: permissions.secure: mismatch between comment and content](https://bugzilla.opensuse.org/show_bug.cgi?id=1157498)~~



## links

- [mail announcement](https://lists.opensuse.org/opensuse-factory/2019-11/msg00327.html)
